### DISCUSSION TITLE
Create flag for search to return single top result

### DISCUSSION THREAD

**Discussion by progS1m** [knqyf263/pet#293] [Ideas]
Hello guys,

I recently stumbled over [espanso.org](https://espanso.org) which seems to be an amazing tool like pet, but with some other possibilities. Since pet is limited to shells I was thinking of a combination of the two tools. Something like setting up a trigger :pet which can fetch the data from the pet commands and presenting a form from where you can select the best matching command for your purpose. 

This would allow you to run pet almost everywhere, like in SSH, VNC, Remote Sessions, apps, etc.

Did not have had the chance to setup something like this, but this probably would be achievable by using something like this: [https://espanso.org/docs/matches/examples/#populating-a-forms-choice-control-with-the-result-of-a-shell-command](https://espanso.org/docs/matches/examples/#populating-a-forms-choice-control-with-the-result-of-a-shell-command)

Have someone of you might had the same idea as me and already something ready to share?
If not what are you thinking about the idea?

Once I have something built on my own I'm going to share it here. 

Would love your feedback, Thanks!

**Comment by RamiAwar** [comment]
Well that's one way of supporting autocomplete in pet, just forcing everyone to install espanso 😁😁

As for your question, I think this request is totally limited by what espanso supports now. I think you might already be able to output a specific snippet in Pet, or maybe it's a feature request that we'll build soon, I can't remember and am away from laptop now. But this is the easy part. Will look into this one for you later.

The other part of the puzzle is being able to call pet from inside espanso. The shell commands should just work considering espanso knows where the pet binary is.

**Comment by RamiAwar** [comment]
@progS1m Yeah don't think this is already supported in Pet, but it's on the roadmap already. You probably need something like this right? 
https://github.com/users/knqyf263/projects/3?pane=issue&itemId=52854992

I think it's on the easy side if you're willing to help out, can guide you through it!

I think I'll get to it in a month or so otherwise.

**Reply by progS1m** [reply]
This seems to be limited to shells only, would be nice for sure. But actually not sufficient for the espanso use case.

**Comment by progS1m** [comment]
I played around a bit with the available features in espanso.
I was able to figure out a quite messy workaround using this espanso config:

```
  - regex: ":pet\\s(?P<input>.*)\\s"
    replace: "{{petform1.command}}"
    vars:
      - name: commands
        type: shell
        params:
          cmd: "grep -A2 -B2 {{input}} ~/.config/pet/snippet.toml | grep -v tag | grep -v output | grep -v snippets | sed 's/^  command = \"\\(.*\\)\"/\\1/'"
      - name: petform1
        type: form
        params:
          layout: |
            Select command:
            [[command]]
          fields:
            command:
              type: list
              values: "{{commands}}"
```

This results in a popup when typing :pet <searchword>  followed by a space, the cool thing is you can run it in any textfield :-)
In the popup I can then select my desired command and it gets pasted in the textfield where I have run the :pet <searchword> string.

<img width="644" alt="image" src="https://github.com/knqyf263/pet/assets/9198744/c79e194b-de03-4b4d-ad72-5d01e72a9221">

What about implementing a new pet search flag, which returns it in a espanso compatible format. This could be used in the cmd: part of espanso.

The best would be if pet could return a formatted output to the std output in the following format:
```
*First command description*
first cli command
*Second command description*
second cli command
```

What about pet search [-q| -t] -r, --raw string

Currently pet search can not be used as it leads into the select mode...
