### ISSUE TITLE
Not able to select snippets with trailing spaces

### ISSUE THREAD

**Issue by shihanng** [knqyf263/pet#107]
This issue can be reproduced with the following snippets file:

```toml
[[snippets]]
  description = "ping (fail A)"
  command = "ping 8.8.8.8"
  tag = ["network", "google    "]
  output = ""

[[snippets]]
  description = "ping (fail B)"
  command = "ping 8.8.8.8   "
  output = ""

[[snippets]]
  description = "ping (pass)"
  command = "ping 8.8.8.8   "
  tag = ["network", "google"]
  output = ""
```

In the case above, we will not be able to select `ping (fail A)` and `ping (fail B)`.

(I've created a PR #108 for this issue.)
