### ISSUE TITLE
Parsing parameters bug

### ISSUE THREAD

**Issue by s3rgeym** [knqyf263/pet#114]
Snippet:

```toml
[[snippets]]
description = "Print a file skipping first N lines"
command = "tail -n +$((<N>+1)) <file>"
tag = ["file system"]
```

Output:

```bash


             ┌─Command(TAB => Select next, ENTER => Execute command):─────────────────────────────────────────┐
             │tail -n +$((<N>+1)) <file>                                                                      │
             │                                                                                                │
             │                                                                                                │
             │                                                                                                │
             └────────────────────────────────────────────────────────────────────────────────────────────────┘

             ┌─<N>+1)) <file>────┐
             │                   │
             └───────────────────┘
```

I am using [this package](https://aur.archlinux.org/packages/pet-bin/).
