### ISSUE TITLE
Garbled characters appear when using variables.

### ISSUE THREAD

**Issue by ofey404** [knqyf263/pet#160]
When I use a snippet with variable, like this:

```toml
[[snippets]]
  description = "ssh without hostkey auth"
  command = "ssh <user>@<host> -o StrictHostKeyChecking=no"
  output = ""
```

I got some garbled characters on the terminal, like:

![image](https://user-images.githubusercontent.com/35857538/110910052-ccff4780-834b-11eb-84eb-5ffb631a3ad2.png)

It's a bit annoying... I am trying to figure out why by myself. I'm grateful if there are anyone who have met this issue before.

My system is fedora 33, garbled characters happens on gnome-terminal and guake terminal, font is system monospace.
